<?php

namespace App\Controllers\Api;

use App\Controllers\BaseController;
use CodeIgniter\API\ResponseTrait;
use App\Models\Api\TransactionModel;
use Mpdf\Mpdf;
class Addc extends BaseController
{
    use ResponseTrait;

   
    private $username = 'DBAPSP';
    private $password = 'y08yhFn1LC';
    private $tokenUrl = 'https://qty.mbme.org:8080/v2/mbme/oauth/token';
     private $paymentUrl = 'https://mobportal.mbme.org:11005/mpay/v1/pay';
private $enquiryUrl = 'https://mobportal.mbme.org:11005/mpay/v1/enquiry';
private $hasrequest = 'https://mobportal.mbme.org:11005/mpay/hashRequest';

    public function index()
    {
        return view('admin/Api/addc/index', [
            'pagetitle' => 'ADDC Payment'
        ]);
    }

      public function getToken()
    {
        $client = \Config\Services::curlrequest();
        $postData = http_build_query([
            'grant_type' => 'password',
            'username'   => $this->username,
            'password'   => $this->password
        ]);

        try {
            $response = $client->post($this->tokenUrl, [
                'headers' => ['Content-Type' => 'application/x-www-form-urlencoded'],
                'body'    => $postData
            ]);

            $result = json_decode($response->getBody(), true);
            $token = $result['access_token'] ?? $result['accessToken'] ?? null;

            return $token
                ? $this->respond(['token' => $token])
                : $this->fail('Token not received', 401);

        } catch (\Exception $e) {
            return $this->failServerError('Token generation failed: ' . $e->getMessage());
        }
    }

public function receipt($id)
{
    $transactionModel = new \App\Models\Api\TransactionModel();
    $userModel = new \App\Models\UsersModel();
    $customerModel = new \App\Models\CustomerModel();

    $transaction = $transactionModel->find($id);
    // Fetch merchant based on customer_name (merchant user_id)
    $merchant = null;
    if (!empty($transaction['customer_name'])) {
        $merchant = $userModel->where('user_id', $transaction['customer_name'])->first();
    }

    // Fetch customer based on created_for (customer_id)
    $customer = null;
    if (!empty($transaction['created_for'])) {
        $customer = $customerModel->where('id', $transaction['created_for'])->first();
    }

    // Fetch customer based on name and mobile (since customer_id doesn't exist in transactions)
    $customer = $customerModel
        ->where('id', $transaction['created_for'])
        ->first();

    try {
        $html = view('admin/Api/addc/receipt_pdf', [
            'txn' => $transaction,
            'merchant' => $merchant,
            'customer' => $customer
        ]);

        $mpdf = new \Mpdf\Mpdf();
        $mpdf->WriteHTML($html);

        return $this->response
            ->setHeader('Content-Type', 'application/pdf')
            ->setHeader('Content-Disposition', 'inline; filename="receipt.pdf"')
            ->setBody($mpdf->Output('', 'S'));

    } catch (\Throwable $e) {
        return $this->response->setStatusCode(500)->setBody('PDF generation failed: ' . $e->getMessage());
    }
}

   
 public function makePayment()
{
    $this->session = \Config\Services::session();
    $client        = \Config\Services::curlrequest();

    $input = $this->request->getJSON(true);

    $accountNumber     = $input['account_number'] ?? null;
    $amountWithoutComm = $input['amount_without_commission'] ?? null;
    $amountWithComm    = $input['amount_with_commission'] ?? null;
    $customerMobile    = $input['customer_mobile'] ?? null;

    $oidFromEnquiry    = $input['oid'] ?? null;          // ✅ must come from fetchBill()
    $userId            = $this->session->get('user_id');
     // ✅ Load user model
    $userModel = new \App\Models\UsersModel();
    $user      = $userModel->find($userId);

    if (empty($user) || empty($user['merchant_uid']) || empty($user['merchant_token'])) {
        return $this->respond([
            'status'  => false,
            'message' => 'Please register in merchant account.'
        ], 400);
    }

    // ✅ Assign merchant credentials
    $merchant_uid   = $user['merchant_uid'];
    $merchant_token = $user['merchant_token'];

    $name              = $userId ?? '';

    // Basic validation
    if (empty($accountNumber) || empty($amountWithoutComm) || empty($amountWithComm) || empty($oidFromEnquiry)) {
        return $this->respond(['status' => false, 'message' => 'Missing parameters or OID'], 400);
    }

    // Flat card fee (if applicable)
    $cardFee                = 55000;
    $totalAmountWithCardFee = $amountWithoutComm + $cardFee;

    /**
     * STEP 1: Hash Request (using SAME oid from enquiry)
     */
    $hashData = [
        "rawData"   => [
            "oid"          => $oidFromEnquiry,   // ✅ reuse enquiry OID
            "uid"          => "$merchant_uid",
            "billerId"     => "41",
            "timestamp"    => "", // will be generated by hashrequest
            "paymentMethod"=> "CARD",
            "cardNumber"   => "1111",
            "authNumber"   => "1111",
            "method"       => "pay",
            "paidAmount"   => "$amountWithoutComm",
            "invoiceAmount"=> "$totalAmountWithCardFee",
            "reqField1"    => $accountNumber
        ],
        "key"       => "$merchant_token",
        "algorithm" => "md5"
    ];

    $hashRes = $client->post($this->hasrequest, [
        'headers'     => ['Content-Type' => 'application/json'],
        'body'        => json_encode($hashData),
        'http_errors' => false,
        'verify'      => false
    ]);

    $hashResult = json_decode($hashRes->getBody(), true);

    if (empty($hashResult['secure_sign']) || empty($hashResult['timestamp'])) {
        return $this->respond(['status' => false, 'message' => 'Failed to get hash request response'], 400);
    }

    $secureSign = $hashResult['secure_sign'];
    $timestamp  = $hashResult['timestamp'];

    /**
     * STEP 2: Make Payment
     */
    $payData = [
        "secureSign"    => $secureSign,
        "oid"           => $oidFromEnquiry,  // ✅ same OID as enquiry
        "uid"           => "$merchant_uid",
        "billerId"      => "41",
        "timestamp"     => $timestamp,
        "paymentMethod" => "CARD",
        "cardNumber"    => "1111",
        "authNumber"    => "1111",
        "method"        => "pay",
        "paidAmount"    => "$amountWithoutComm",
        "invoiceAmount" => "$totalAmountWithCardFee",
        "reqField1"     => "$accountNumber"
    ];

    $paymentRes = $client->post(
        'https://mobportal.mbme.org:11005/mpay/v1/pay',
        [
            'headers'     => ['Content-Type' => 'application/json'],
            'body'        => json_encode($payData),
            'http_errors' => false,
            'verify'      => false
        ]
    );

    $paymentResult = json_decode($paymentRes->getBody(), true);

    // Check if transaction succeeded
   
$respCode     = $paymentResult['respCode'] ?? null;
$innerStatus  = ($paymentResult['status'] == 1); // API uses 1 for success
$transactionId= $paymentResult['data']['transactionId'] ?? null;

// Define success properly
$isSuccess = ($respCode == 0 && $innerStatus);
$status    = $isSuccess ? 'SUCCESS' : 'FAILED';
    /**
     * STEP 3: Save Transaction
     */
    $model = new \App\Models\TransactionModel();
    $model->insert([
        'transaction_id' => $transactionId,
        'account_number' => $accountNumber,
        'amount'         => $amountWithoutComm,
        'customer_name'  => $userId,
        'customer_mobile'=> $customerMobile,
        'status'         => $status,
        'Payment_type'   => 'ADDC',
         'OID'            =>$oidFromEnquiry,
        'response'       => json_encode($paymentResult)
    ]);

    /**
     * STEP 4: Deduct Wallet
     */
        $userId = $this->session->get('user_id');

    $usersModel = new \App\Models\UsersModel();
    $user       = $usersModel->find($userId);

    if ($user) {
        $remainingWallet = $user['wallet'] - $amountWithoutComm;

        $usersModel->update($userId, ['wallet' => $remainingWallet]);

        // Log wallet transaction
        $walletModel = new \App\Models\WalletModel();
        $walletModel->insert([
            'user_id'         => $userId,
            'amount'          => $amountWithoutComm,
            'transaction_type'=> 'debit',
            'Payment_type'    => 'ADDC',
            'created_at'      => date('Y-m-d H:i:s')
        ]);

        $this->session->set('wallet', $remainingWallet);
    }

    return $this->respond([
        'status'  => ($status === "SUCCESS"),
        'message' => ($status === "SUCCESS") ? 'Payment processed' : 'Payment failed',
        'data'    => $paymentResult
    ]);
}







public function fetchBill()
{
        $this->session = \Config\Services::session();

    $input = $this->request->getJSON(true);
    $account = $input['account_number'] ?? '';
    $reqType = $input['req_type'] ?? 'AccountID';

    if (!$account) {
        return $this->failValidationErrors('Account number is required.');
    }

   $client = \Config\Services::curlrequest();
    $userId = $this->session->get('user_id');

    // ✅ Load user model
    $userModel = new \App\Models\UsersModel();
    $user      = $userModel->find($userId);

    if (empty($user) || empty($user['merchant_uid']) || empty($user['merchant_token'])) {
        return $this->respond([
            'status'  => false,
            'message' => 'Please register in merchant account.'
        ], 400);
    }

    // ✅ Assign merchant credentials
    $merchant_uid   = $user['merchant_uid'];
    $merchant_token = $user['merchant_token'];

    try {
        

        $hashData = [
        "rawData" => [
            "oid"       => "", // or your order ID
            "uid"       => "$merchant_uid",
            "billerId"  => "41",
            "method"    => "balance",
            "reqField1" => $account,
            "reqField2" => "AccountID",
            "timestamp" => "" // will be generated if needed
           ],
         "key"       => "$merchant_token",
         "algorithm" => "md5"
        ];

       $hashRes = $client->post($this->hasrequest, [
            'headers' => ['Content-Type' => 'application/json'],
            'body'    => json_encode($hashData),
            'http_errors' => false,
            'verify' => false // 🚨 temporary bypass
        ]);
        $hashResult = json_decode($hashRes->getBody(), true);
       
        
 log_message('error', '🔹 HASH REQUEST DATA: ' . json_encode($hashData));
        log_message('error', '🔹 HASH RESPONSE: ' . $hashRes->getBody());

        if (empty($hashResult['oid'])) {
            log_message('error', '❌ Missing OID in hash response');
            return $this->respond(['error' => 'Failed to get oid from hash request'], 400);
        }

        $oid = $hashResult['oid'];
          $secure_sign = $hashResult['secure_sign'];
        $timestamp = $hashResult['timestamp'] ?? time();

        // 2️⃣ Balance enquiry
        $balanceData = [
            'secureSign' => $secure_sign,
            'oid'        => $oid,
            "uid"       => "$merchant_uid",
            'billerId'   => '41',
            'method'     => 'balance',
            'reqField1'  => $account,
            'reqField2'  => "AccountID",
            'timestamp'  => $timestamp
        ];

        $balanceRes = $client->post('https://mobportal.mbme.org:11005/mpay/v1/enquiry', [
            'headers' => ['Content-Type' => 'application/json'],
            'body'    => json_encode($balanceData),
            'http_errors' => false,
            'verify' => false // 🚨 temporary bypass
            ]);

        // return $this->respond(json_decode($balanceRes->getBody(), true));
         $balanceResult = json_decode($balanceRes->getBody(), true);
   log_message('error', '🔹 BALANCE REQUEST DATA: ' . json_encode($balanceData));
        log_message('error', '🔹 BALANCE RESPONSE: ' . $balanceRes->getBody());

        return $this->respond([
            'status'       => true,
            'message'      => 'Balance fetched',
            'data'         => $balanceResult['data'] ?? [],
            'oid'          => $oid,
            'secure_sign'  => $secure_sign,
            'timestamp'    => $timestamp
        ]);

    } catch (\Exception $e) {
        return $this->failServerError('Error fetching bill: ' . $e->getMessage());
    }
}

    public function fetchBillFromPostman()
{
    $input   = $this->request->getJSON(true);
    $account = $input['account_number'] ?? '';

    if (!$account) {
        return $this->failValidationErrors('Account number is required.');
    }

    $client = \Config\Services::curlrequest();

    try {
        /**
         * STEP 1: Hash Request (same as admin fetchBill)
         */
        $hashData = [
            "rawData" => [
                "oid"       => "", // leave empty, system will generate
                "uid"       => "344",
                "billerId"  => "41", // ✅ AADC billerId
                "method"    => "balance",
                "reqField1" => $account,
                "reqField2" => "AccountID",
                "timestamp" => ""   // generated by hash service
            ],
            "key"       => "5596e86a42755cd1ef08b603318d5bbe77362625ce41a3a9063e4baff669cbd3",
            "algorithm" => "md5"
        ];

        $hashRes = $client->post($this->hasrequest, [
            'headers'     => ['Content-Type' => 'application/json'],
            'body'        => json_encode($hashData),
            'http_errors' => false,
            'verify'      => false
        ]);

        $hashResult = json_decode($hashRes->getBody(), true);

        log_message('error', '🔹 FETCH BILL (Postman) HASH DATA: ' . json_encode($hashData));
        log_message('error', '🔹 FETCH BILL (Postman) HASH RESPONSE: ' . $hashRes->getBody());

        if (empty($hashResult['oid'])) {
            return $this->respond(['error' => 'Failed to get oid from hash request'], 400);
        }

        $oid        = $hashResult['oid'];
        $secureSign = $hashResult['secure_sign'];
        $timestamp  = $hashResult['timestamp'] ?? time();

        /**
         * STEP 2: Balance Enquiry
         */
        $balanceData = [
            'secureSign' => $secureSign,
            'oid'        => $oid,
            "uid"        => "344",
            'billerId'   => '41', // ✅ AADC biller
            'method'     => 'balance',
            'reqField1'  => $account,
            'reqField2'  => "AccountID",
            'timestamp'  => $timestamp
        ];

        $balanceRes = $client->post('https://mobportal.mbme.org:11005/mpay/v1/enquiry', [
            'headers'     => ['Content-Type' => 'application/json'],
            'body'        => json_encode($balanceData),
            'http_errors' => false,
            'verify'      => false
        ]);

        $balanceResult = json_decode($balanceRes->getBody(), true);

        log_message('error', '🔹 FETCH BILL (Postman) BALANCE REQUEST: ' . json_encode($balanceData));
        log_message('error', '🔹 FETCH BILL (Postman) BALANCE RESPONSE: ' . $balanceRes->getBody());

        return $this->respond([
            'status'      => true,
            'message'     => 'Balance fetched',
            'data'        => $balanceResult['data'] ?? [],
            'oid'         => $oid,
            'secure_sign' => $secureSign,
            'timestamp'   => $timestamp
        ]);

    } catch (\Exception $e) {
        return $this->failServerError('Error fetching bill (Postman): ' . $e->getMessage());
    }
}

    public function makePaymentFromPostman()
{
    $client = \Config\Services::curlrequest();
    $input  = $this->request->getJSON(true);

    $accountNumber     = $input['account_number'] ?? null;
    $amountWithoutComm = $input['amount_without_commission'] ?? null;
    $amountWithComm    = $input['amount_with_commission'] ?? null;
    $customerMobile    = $input['customer_mobile'] ?? null;

    $oidFromEnquiry    = $input['oid'] ?? null;        // ✅ must come from fetchBill()
    $userId            = $input['merchant_id'] ?? null; // ✅ Postman provides merchant_id
    $name              = $userId ?? '';

    // Basic validation
    if (empty($accountNumber) || empty($amountWithoutComm) || empty($amountWithComm) || empty($oidFromEnquiry)) {
        return $this->respond(['status' => false, 'message' => 'Missing parameters or OID'], 400);
    }

    // Flat card fee (if applicable)
    $cardFee                = 55000;
    $totalAmountWithCardFee = $amountWithoutComm + $cardFee;

    /**
     * STEP 1: Hash Request (using SAME oid from enquiry)
     */
    $hashData = [
        "rawData"   => [
            "oid"           => $oidFromEnquiry,
            "uid"           => "344",
            "billerId"      => "41",
            "timestamp"     => "",
            "paymentMethod" => "CARD",
            "cardNumber"    => "1111",
            "authNumber"    => "1111",
            "method"        => "pay",
            "paidAmount"    => "$amountWithoutComm",
            "invoiceAmount" => "$totalAmountWithCardFee",
            "reqField1"     => $accountNumber
        ],
        "key"       => "5596e86a42755cd1ef08b603318d5bbe77362625ce41a3a9063e4baff669cbd3",
        "algorithm" => "md5"
    ];

    $hashRes = $client->post($this->hasrequest, [
        'headers'     => ['Content-Type' => 'application/json'],
        'body'        => json_encode($hashData),
        'http_errors' => false,
        'verify'      => false
    ]);

    $hashResult = json_decode($hashRes->getBody(), true);

    if (empty($hashResult['secure_sign']) || empty($hashResult['timestamp'])) {
        return $this->respond(['status' => false, 'message' => 'Failed to get hash request response'], 400);
    }

    $secureSign = $hashResult['secure_sign'];
    $timestamp  = $hashResult['timestamp'];

    /**
     * STEP 2: Make Payment
     */
    $payData = [
        "secureSign"    => $secureSign,
        "oid"           => $oidFromEnquiry,
        "uid"           => "344",
        "billerId"      => "41",
        "timestamp"     => $timestamp,
        "paymentMethod" => "CARD",
        "cardNumber"    => "1111",
        "authNumber"    => "1111",
        "method"        => "pay",
        "paidAmount"    => "$amountWithoutComm",
        "invoiceAmount" => "$totalAmountWithCardFee",
        "reqField1"     => "$accountNumber"
    ];

    $paymentRes = $client->post(
        'https://mobportal.mbme.org:11005/mpay/v1/pay',
        [
            'headers'     => ['Content-Type' => 'application/json'],
            'body'        => json_encode($payData),
            'http_errors' => false,
            'verify'      => false
        ]
    );

    $paymentResult = json_decode($paymentRes->getBody(), true);

    // ✅ Status check
    $respCode     = $paymentResult['respCode'] ?? null;
    $innerStatus  = ($paymentResult['status'] == 1);
    $transactionId= $paymentResult['data']['transactionId'] ?? null;

    $isSuccess = ($respCode == 0 && $innerStatus);
    $status    = $isSuccess ? 'SUCCESS' : 'FAILED';

    /**
     * STEP 3: Save Transaction
     */
    $txnModel = new \App\Models\TransactionModel();
    $txnModel->insert([
        'transaction_id'  => $transactionId,
        'account_number'  => $accountNumber,
        'amount'          => $amountWithoutComm,
        'customer_name'   => $name,
        'customer_mobile' => $customerMobile,
        'status'          => $status,
        'Payment_type'    => 'ADDC',
        'OID'             => $oidFromEnquiry,
        'response'        => json_encode($paymentResult)
    ]);

    /**
     * STEP 4: Deduct Wallet
     */
    $usersModel = new \App\Models\UsersModel();
    $user       = $usersModel->find($userId);

    if ($user) {
        $remainingWallet = $user['wallet'] - $amountWithoutComm;

        $usersModel->update($userId, ['wallet' => $remainingWallet]);

        $walletModel = new \App\Models\WalletModel();
        $walletModel->insert([
            'user_id'          => $userId,
            'amount'           => $amountWithoutComm,
            'transaction_type' => 'debit',
            'Payment_type'     => 'ADDC',
            'created_at'       => date('Y-m-d H:i:s')
        ]);
    }

    return $this->respond([
        'status'  => ($status === "SUCCESS"),
        'message' => ($status === "SUCCESS") ? 'Payment processed' : 'Payment failed',
        'data'    => $paymentResult
    ]);
}

   public function reports()
    {
        $this->session = \Config\Services::session();
        $userId = $this->session->get('user_id');
        $model = new \App\Models\Api\TransactionModel();

        $builder = $model->where('customer_name', $userId)
                        ->where('Payment_type', 'ADDC');

        // Filtering logic
        $startDate = $this->request->getGet('start_date');
        $endDate   = $this->request->getGet('end_date');
        $search    = $this->request->getGet('search');

        if ($startDate) {
            $builder->where('DATE(created_at) >=', $startDate);
        }
        if ($endDate) {
            $builder->where('DATE(created_at) <=', $endDate);
        }
        if ($search) {
            $builder->groupStart()
                ->like('account_number', $search)
                ->orLike('transaction_id', $search)
                ->groupEnd();
        }

        $transactions = $builder->orderBy('created_at', 'DESC')->findAll();

        return view('admin/Api/addc/report', [
            'transactions' => $transactions,
            'pagetitle' => 'ADDC Payment Reports'
        ]);
    }


}
